# Change these first
owner: ZingLix # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: ZingLix Blog
    url: https://zinglix.xyz
  - name: Alala Console
    url: https://alala.zinglix.xyz
  - name: Annotation Platform
    url: https://a.zinglix.xyz
  - name: frp 
    url: https://frp.zinglix.xyz
    expectedStatusCodes:
      - 200
      - 401
  - name: ZingLix Share
    url: https://x.zinglix.xyz
  - name: ZingLix Blog Mirror
    url: https://blog.zinglix.xyz
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upp.zinglix.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ZingLix Upptime
  introTitle: "ZingLix Uptime Monitor"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Blog
      href: https://zinglix.xyz

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
